### ISSUE TITLE
new package for blogging?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/rodev#13]
I'm starting to wonder whether there should be a very small package called `roblog` (instead of having stuff here, this package being for package developers). Cc @stefaniebutland 

- [ ] It'd have the template for blog posts (easy).

- [ ] It'd include the script I've discussed in #5 (not too hard but needs good documentation).

- [ ] It'd define a `ggplot2` theme. 
    * The idea would be to use `hrbrthemes` at first since it's fine, and to use `theme_set` in the first chunk of the blog post template. 
    * The theme would define a good text size for all parts of a plot.
    * I hope it's possible to add default color scales this way the default scales would be `viridis` and `colorblindr` palettes for continuous and discrete variables by default.

- [ ] The package would have a check post function. It'd check the YAML, the relative links, the spelling, and whether all figures have an alternative caption. Parts of this could be added to a check of PRs.

**Comment by maelle** [comment]
Nice to have but less crucial: a function for scanning the text for packages names to add links to their website. Or even an add-in to add the link for a selected package name.

**Comment by sckott** [comment]
Good idea - sounds good

**Comment by stefaniebutland** [comment]
sounds good indeed. Would probably help blog post authors not have to think through yet another process after onboarding.

One closely related for technotes too.

**Comment by maelle** [comment]
The package should also have a function creating the excerpt and URL for the discuss post (easy to create that URL from info in the YAML)

**Comment by maelle** [comment]
https://r-resources.massey.ac.nz/rmarkdown/

**Comment by maelle** [comment]
Adventures to be followed over at https://github.com/ropenscilabs/roblog
