### ISSUE TITLE
tests notes

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/rodev#22]
- where does done come from: https://github.com/ropenscilabs/rodev/blob/master/tests/testthat/helper.R#L42

**Comment by maelle** [comment]
Should I expect other notes?

Testing is in general poor cf #16

**Comment by sckott** [comment]
i thought I would add others, but didn't see any other itesm

**Comment by maelle** [comment]
Ok! I simplified testing and increased coverage today.
