### ISSUE TITLE
add_ro_fnd: author/maintainer and Authors@R fields

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/rodev#23]
if a DESCRIPTION file already has Author and Maintainer fields, , then `add_ro_fnd` adds `Authors@R` - i thought you weren't supposed to have both of these, or am I wrong?

and then in r check

```
✔  checking for future file timestamps (514ms)
N  checking DESCRIPTION meta-information ...
   Authors@R field gives no person with maintainer role, valid email
   address and non-empty name.
```

**Comment by maelle** [comment]
Ah interesting! I should check the field already exists then, for onboarded packages we require the use of Authors@R

**Comment by sckott** [comment]
> or onboarded packages we require the use of Authors@R

okay, sounds good. 

probably should still check if it exists already and modify it if so, just in case

**Comment by maelle** [comment]
See PR #25 where I requested your review 😉

**Comment by maelle** [comment]
@sckott happy with the current behavior, i.e. informative error when no Authors@R field?

**Comment by sckott** [comment]
yes, happy with that
