### ISSUE TITLE
helper to create a blog post for rOpenSci

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/rodev#5]
Not too sure how it'd work. But here is a brain dump.

It'd help avoiding

* copy pasting images and stuff in the right subdirectory of roweb2

* inserting images links in awkward ways

Cf @aedobbyn's  #[post in the discussion forum](https://discuss.ropensci.org/t/best-blog-post-writing-practices-re-image-file-paths-and-footnotes/)

When one has a blogdown blog (which I don't) if I understood correctly creating a new post is super straightforward.

The helper and its docs would also make it clearer how to keep track of the Rmd that leads to an md. For reproducibility purposes should it live in roweb2 repo? Or would the easiest thing be to recommend people create a distinct project with Rmd, images in an image folder, figures etc., render a md there (using a template for the Rmd) and then the helper would help transforming the whole thing (including changing paths to figures and images) for a PR to the roweb2 repo?

If the blog post is about an onboarded package then the user could supply the onboarding issue number and some fields could be filled automatically (even a few template lines in the end with <edit me, thank your reviewers here if you haven't done that in the rest of the post>, also something corresponding to "consider ending by pointing to open issues that readers might work on")

**Comment by maelle** [comment]
Oh and in the "separate repo scenario" the blog post could include a link to that repo so that readers can easily find the Rmd.

One problem with a separate repo is synchronisation after pull request comments, i.e. the author would modify... what? Their separate repo and then run a function again to update their branch of roweb2?

**Comment by maelle** [comment]
The reason I like the "separate repo scenario" is that one doesn't need to clone the whole website locally and to be overwhelmed by its structure.

**Comment by maelle** [comment]
Thanks for your feedback @aedobbyn!

I think the helper could work like say `usethis::create_package` and instead create a template project with Rmd + img folder.

So there'd be

* `create_blogpost_project`. The html preview would be the local rendering, not very fancy but I think enough at least in a first version.

* `submit_blogpost` would automatically fork the website (granted the user deleted the fork of the website they had if they had one... or that it has no conflict and the function could synchronize it?), and create stuff in the fork based on the .md created previously and on its images. The "todo" for the author would be to submit a PR. (the problem here are updates, based on the review of the PR a `update_blogpost` function would be needed) OR something more elaborate involving submodules. 🤔 
 
Scott said git submodules could be useful here (Amanda I know you've recently started using them 😜 ), I need to think a bit about that (I "know" submodules because of https://github.com/lockedatapublished/superbuild )

**Comment by aedobbyn** [comment]
Hmm. I think this could use some tinkering on a small toy repo plus maybe a whiteboard to see what the best approach is. Agreed that interacting with the post once it’s been added to the main repo might be the main challenge here. I wonder if there are any examples of similar projects?

**Comment by maelle** [comment]
this helper should also remind to have good chunk names or labels in order to create proper alternative text for figures for accessibility.

**Comment by maelle** [comment]
Still hacky but minimal workflow ✅ 

* [`create_post_project`](https://github.com/ropenscilabs/rodev/blob/master/R/blog_posts.R#L11) creates a folder based on a dlug, inside the current directory. It adds either post.Rmd+post.md or post.md with right slug in the YAML header, and a README.md. See https://github.com/maelle/yay It also adds an Rproj and opens it if `rstudioapi::isAvailable()`

* [`prepare_fork`](https://github.com/ropenscilabs/rodev/blob/master/R/blog_posts.R#L81) currently creates a fork (needs `gh` and a GITHUB_PAT). It needs gh_username. Will probably fail if existing fork and wrong gh_username compared to GITHUB_PAT but could be improved of course. Once the fork is created it reads post.md in post_project_path and 1) gets slug and date from the YAML header, 2) replaces links to images with img/blabla as needed in https://github.com/ropensci/roweb2#contributing-a-blog-post 3) uploads post to the fork 4) uploads all images to the fork.

Fork for yay example post https://github.com/maelle/roweb2

**Comment by maelle** [comment]
still unsolved are updates after a PR review

**Comment by maelle** [comment]
Note that I do not want to depend on `git2r` because of its not working on Windows for push 😹 😭

**Comment by maelle** [comment]
Btw summary of the reasons for the separate minimal repo:

* Having the Rmd there.

* Having raw data that might be needed (both these items for reproducibility without needing to put many things in the website repo).

* Not having to clone the website locally.

* Not having to deal with the structure of the website.

**Comment by aedobbyn** [comment]
This is awesome!! 🙌 Still have to try it out but the code makes sense. I'll have a think on the updating issue that doesn't use `git2r`.

**Comment by maelle** [comment]
Thx for the feedback @aedobbyn! And sorry that the helpers will come too late for your post 😢

Reg updating I was thinking i should just try to overwrite the post in the fork bqsed on the post in the minimal repo, maybe it will just work.🤔 will try that tomorrow

**Comment by aedobbyn** [comment]
This is so awesome!

Is it your plan already to abstract away the copying of post content, `img_dir`, etc. into a separate function like `port_content()`?

Seems useful for `rodev::prepare_fork()` to allow for multiple posts but maybe not crucial to the MVP here.

**Comment by maelle** [comment]
@aedobbyn 

1. Further adventures in https://github.com/ropenscilabs/roblog
2. Are you ok with my including you as "ctb" of `roblog` for all your help in this thread?

**Comment by aedobbyn** [comment]
@maelle sure, thanks for asking! 😄

**Comment by maelle** [comment]
Done! 😁
